import CryptoJS from 'crypto-js';
declare type CryptoJS = {
    AES: any,
    DES: any,
    EvpKDF: any,
    HmacMD5: any,
    HmacRIPEMD160: any,
    HmacSHA1: any,
    HmacSHA3: any,
    HmacSHA224: any,
    HmacSHA256: any,
    HmacSHA384: any,
    HmacSHA512: any,
    MD5: any,
    PBKDF2: any,
    RC4: any,
    RC4Drop: any,
    RIPEMD160: any,
    Rabbit: any,
    RabbitLegacy: any,
    SHA1: any,
    SHA3: any,
    SHA224: any,
    SHA256: any,
    SHA384: any,
    SHA512: any,
    TripleDES: any,
    algo: any,
    enc: any,
    format: any,
    kdf: any,
    lib: any,
    mode: any,
    pad: any,
    x64: any
}
